kind: Service
apiVersion: v1
metadata:
  name: flask-service
  namespace: flask  
  labels:
    app: flask
spec:
  type: NodePort
  selector:
     app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000  
